name: check

on:
  workflow_dispatch:
    inputs:
      keyword:
        description: 'Keyword'     
        required: false
      number_from:
        description: 'from number (4 digits)'
        required: false
      number_to:
        description: 'to number (4 digits)'
        required: false
      connssh:
        description: 'Connect to ssh'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@v1

    - name: check world
      env:
        WORKFLOW_SCKEY: ${{ secrets.workflow_sckey }}
        WORKFLOW_CHECK_SH: ${{ secrets.workflow_check_sh }}
        WORKFLOW_TOKEN: ${{ secrets.workflow_token }}
        KEYWORD: ${{ github.event.inputs.connssh.keyword }}
        NUMBER_FROM: ${{ github.event.inputs.number_from }}
        NUMBER_TO: ${{ github.event.inputs.number_to }}
        WAIT_TO_CONNSSH: ${{ github.event.inputs.connssh }}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
        if [ $WAIT_TO_CONNSSH = true ]; then
          bash ./send_tmate_session.sh "check_"
        else
          echo $WORKFLOW_CHECK_SH | base64 -d > ./check.sh
          sudo bash ./check.sh
        fi
