name: check

on:
  workflow_dispatch:
    inputs:
      keyword:
        description: 'Keyword'     
        required: false
      number_from:
        description: 'from number'
        required: false
        type: number
      number_to:
        description: 'to number'
        required: false
        type: number
      connssh:
        description: 'Connect to ssh'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@v1

    - name: hello world
      env:
        DEBIAN_FRONTEND: noninteractive
        WORKFLOW_SCKEY: ${{ secrets.workflow_sckey }}
        WORKFLOW_CHECK_SH: ${{ secrets.workflow_check_sh }}
        WORKFLOW_TOKEN: ${{ secrets.workflow_token }}
        KEYWORD: ${{ github.event.inputs.keyword }}
        WAIT_TO_CONNSSH: ${{ github.event.inputs.connssh }}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
        if [ $WAIT_TO_CONNSSH = true ]; then
          bash ./send_tmate_session.sh "hello_"
        else
          echo $WORKFLOW_CHECK_SH | base64 -d > ./check.sh
          sudo bash ./check.sh "$KEYWORD"
        fi
