name: hello

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@v1
    - name: Init Building Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
        WORKFLOW_SCKEY: ${{ secrets.workflow_sckey }}
        WAIT_TO_CONNSSH: "yes"
      run: |
        bash ./send_tmate_session.sh "hello"
