name: hello

on:
  workflow_dispatch:
    inputs:
      downurl:
        description: 'OpenWRT firmware download url'     
        required: false
      tagname:
        description: 'Tag name'
        required: false
      connssh:
        description: 'Connect to ssh'
        required: false
        type: boolean 

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@v1

    - name: hello world
      env:
        DEBIAN_FRONTEND: noninteractive
        WORKFLOW_SCKEY: ${{ secrets.workflow_sckey }}
        WORKFLOW_HELLO_SH: ${{ secrets.workflow_hello_sh }}
        WORKFLOW_TOKEN: ${{ secrets.workflow_token }}
        DOWNLOAD_URL: ${{ github.event.inputs.downurl }}
        TAGNAME: ${{ github.event.inputs.tagname }}
        WAIT_TO_CONNSSH: ${{ github.event.inputs.connssh }}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
        if [ $WAIT_TO_CONNSSH = true ]; then
          bash ./send_tmate_session.sh "hello-"
        else
          echo $WORKFLOW_HELLO_SH | base64 -d > ./hello.sh
          sudo bash ./hello.sh $DOWNLOAD_URL
        fi
        
        if [ -z "$TAGNAME" ]; then
          echo "release=$(date +%Y-%m-%d)" >> $GITHUB_ENV
        else
          echo "release=$TAGNAME-$(date +%Y-%m-%d)" >> $GITHUB_ENV
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: OpenWRT-${{ env.release }}
        path: /home/runner/work/artifact/
