name: NanoPi R2S ImmortalWrt

on:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/NanoPi R2S ImmortalWrt.yml'

jobs:
  ImmortalWrt-18_06:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Init Building Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        if [ "`shopt dotglob | awk -F ' ' '{print $2}'`" == "on" ]; then
          mv -f ./* /tmp/
        else
          shopt -s dotglob
          mv -f ./* /tmp/
          shopt -u dotglob
        fi
        docker rmi $(docker images -q)
        sudo -E apt-get remove -y --purge azure-cli ghc zulu* hhvm llvm* firefox google* dotnet* powershell mysql* php* mssql-tools msodbcsql17 android*
        sudo -E apt-get update -y
        sudo -E apt-get full-upgrade -y
        sudo -E apt-get install -y build-essential asciidoc binutils bzip2 coreutils gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-8 gcc++-8 gcc-8-multilib g++-8-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python python3 python-pip python3-pip python3-setuptools python-ply python3-ply haveged lrzsz device-tree-compiler scons antlr3 gperf ecj fastjar re2c xz-utils tar zip
        sudo -EH pip3 install -U pyrogram tgCrypto
        for i in $(ls /usr/bin/*-8); do sudo -E ln -sf $i ${i%%-8*}; done 
        sudo -E ln -sf /usr/include/asm-generic /usr/include/asm
        sudo -E apt-get autoremove -y --purge
        sudo -E apt-get clean -y
        sudo -E swapoff -a
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android /opt/ghc /swapfile
    - name: Clone Source
      run: |
        cd "/home/runner"
        git clone --branch "openwrt-18.06-k5.4" --single-branch "https://github.com/immortalwrt/immortalwrt" "immortalwrt"
        curl -o /home/runner/immortalwrt/1806-config.seed https://raw.githubusercontent.com/1715173329/nanopi-r2s-openwrt/master/configs/1806-config.seed
        curl -o /home/runner/immortalwrt/1806-modify_for_r2s.patch https://raw.githubusercontent.com/1715173329/nanopi-r2s-openwrt/master/patchs/1806-modify_for_r2s.patch
        sudo chown -R runner:runner "immortalwrt"
        cd "/home/runner/immortalwrt"
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        patch -p1 < "./1806-modify_for_r2s.patch"
        sed -i 's/192.168.1.1/192.168.2.1/g' package/base-files/files/bin/config_generate
#    - name: hello world
#      env:
#        WORKFLOW_SCKEY: ${{ secrets.workflow_sckey }}
#      run: |
#        bash /tmp/send_tmate_session.sh "NanoPi R2S immortalwrt_Plus 1806-"
    - name: Build ImmortalWrt-18.06
      run: |
        cd "/home/runner/immortalwrt"
        cp -f "./1806-config.seed" ".config"
        echo '
        CONFIG_PACKAGE_aria2=y
        CONFIG_PACKAGE_ariang=y
        CONFIG_PACKAGE_luci-app-aria2=y
        CONFIG_PACKAGE_luci-i18n-aria2-zh-cn=y
        ' >> .config
        make defconfig
        make -j$[$(nproc)+1]
        mv -f "bin/targets/rockchip/armv8/immortalwrt-rockchip-armv8-friendlyarm_nanopi-r2s-ext4-sysupgrade.img.gz" "../immortalwrt-18.06-rockchip-armv8-friendlyarm_nanopi-r2s-ext4-sysupgrade.img.gz"
        mv -f "bin/targets/rockchip/armv8/immortalwrt-rockchip-armv8-friendlyarm_nanopi-r2s-squashfs-sysupgrade.img.gz" "../immortalwrt-18.06-rockchip-armv8-friendlyarm_nanopi-r2s-squashfs-sysupgrade.img.gz"
        mv -f "bin/targets/rockchip/armv8/sha256sums" "../immortalwrt-18.06-sha256sums"
    - name: Rebuild ImmortalWrt-18.06 to Collect Error Log
      if: failure()
      run: |
        cd "/home/runner/immortalwrt"
        make -j1 V=s
        mv -f "bin/targets/rockchip/armv8/immortalwrt-rockchip-armv8-friendlyarm_nanopi-r2s-ext4-sysupgrade.img.gz" "../immortalwrt-18.06-rockchip-armv8-friendlyarm_nanopi-r2s-ext4-sysupgrade.img.gz"
        mv -f "bin/targets/rockchip/armv8/immortalwrt-rockchip-armv8-friendlyarm_nanopi-r2s-squashfs-sysupgrade.img.gz" "../immortalwrt-18.06-rockchip-armv8-friendlyarm_nanopi-r2s-squashfs-sysupgrade.img.gz"
        mv -f "bin/targets/rockchip/armv8/sha256sums" "../immortalwrt-18.06-sha256sums"
    - name: Upload ImmortalWrt-18.06 SHA256SUM Hash
      uses: actions/upload-artifact@v2
      with:
        name: immortalwrt-18.06-sha256sums
        path: /home/runner/immortalwrt-18.06-sha256sums
    - name: Upload ImmortalWrt-18.06 EXT4 Firmware
      uses: actions/upload-artifact@v2
      with:
        name: immortalwrt-18.06-rockchip-armv8-friendlyarm_nanopi-r2s-ext4-sysupgrade.img.gz
        path: /home/runner/immortalwrt-18.06-rockchip-armv8-friendlyarm_nanopi-r2s-ext4-sysupgrade.img.gz
    - name: Upload ImmortalWrt-18.06 SquashFS Firmware
      uses: actions/upload-artifact@v2
      with:
        name: immortalwrt-18.06-rockchip-armv8-friendlyarm_nanopi-r2s-squashfs-sysupgrade.img.gz
        path: /home/runner/immortalwrt-18.06-rockchip-armv8-friendlyarm_nanopi-r2s-squashfs-sysupgrade.img.gz
