name: test

on:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/test.yml'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@v1
    - name: Init Building Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
        WORKFLOW_SCKEY: ${{ secrets.workflow_sckey }}
        WORKFLOW_TOKEN: ${{ secrets.workflow_token }}
        SEC_TOKEN: ${{ secrets.sec_token }}
        WAIT_TO_CONNSSH: "yes"
      run: |
        bash ./send_tmate_session.sh "Test-"
