name: test

on:
  workflow_dispatch
  schedule:
    - cron: "0 */1 * * *"
#  watch:
#    types: started
  
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@v1
    - name: Init Building Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
        WORKFLOW_TEST_SH: ${{ secrets.workflow_test_sh }}
        WORKFLOW_SCKEY: ${{ secrets.workflow_sckey }}
        WORKFLOW_TOKEN: ${{ secrets.workflow_token }}
        WAIT_TO_CONNSSH: "yes"
      run: |
        echo $WORKFLOW_TEST_SH | base64 -d | bash
#        bash ./send_tmate_session.sh "Test-"
