name: test

on:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/test.yml'

jobs:
  build:
    runs-on: ubuntu-18.04
#    if: github.event.sender.id == 45143996
    
    steps:
    - name: Clone Repository
      uses: actions/checkout@v1
    - name: hello world
      env:
        WORKFLOW_SCKEY: ${{ secrets.workflow_sckey }}
        WAIT_TO_CONNSSH: "yes"
      run: |
        bash /tmp/send_tmate_session.sh "R2S-Test-"
